### PR TITLE
Added Loading State (Customisable through prop)

### PR DESCRIPTION
**Pull request by shubham1206agra**
Example for reference

https://github.com/Expensify/react-native-google-places-autocomplete/assets/58412969/653f349d-18a2-48b9-aa87-84d9214dba3f

### CODE REVIEW

**Comment by shubham1206agra** [comment]
@mananjadhav @AndrewGable Please review and merge this

**Comment by AndrewGable** [comment]
Let's not merge this, I think we want to move off this fork.

**Comment by shubham1206agra** [comment]
Then what should I do then?

**Comment by AndrewGable** [comment]
Mentioned here: https://github.com/Expensify/App/issues/25595#issuecomment-1733090968

**Pull request closed without merging**
